FUNCTION FIBONACCI(VAL X);
	BEGIN
		IF X = 0 THEN
			FIBONACCI := 0
		ELSE
			BEGIN
				IF X = 1 THEN
					FIBONACCI := 1
				ELSE
					FIBONACCI := CALL FIBONACCI(X-1) + CALL FIBONACCI(X-2);
			END
	END;
BEGIN
	WRITELN(CALL FIBONACCI(19));
END.