PROCEDURE HANOI(VAL NUM,SRC,DST,SPR);
	BEGIN
		IF NUM = 1 THEN
			BEGIN
				WRITELN(SRC, DST);
			END
		ELSE
			BEGIN
				CALL HANOI(NUM-1,SRC,SPR,DST);
				CALL HANOI(1,SRC,DST,SPR);
				CALL HANOI(NUM-1,SPR,DST,SRC);
			END
	END;
BEGIN
	CALL HANOI(4,1,3,2);
END.